### ISSUE TITLE
auth-server项目里到处都是不全的代码

### ISSUE THREAD

**Issue by jianwwpro** [minlingchao1/auth-center#1]
比如User、Role等对象，没有get和set方法，没有build方法，却到处在调用。

**Comment by codecraftm** [comment]
这个不是不全，是用了jar包的, lombok ，建议你学习一下，可以省略这些基础方法

**Comment by codecraftm** [comment]
这个你需要在ide里面下一个支持的插件就好了

**Comment by shenzhuan** [comment]
能加个qq吗  1439226817  cas怎么配置还是不懂

**Comment by codecraftm** [comment]
738509878

**Comment by jianwwpro** [comment]
那就知道了，这个确实比较隐，不说明一下对没用过lombok的还真不好弄。多谢
